apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  AUTH_DB_URL: mongodb+srv://Simha:Simha@cluster0.w56omxb.mongodb.net/Authentication?retryWrites=true&w=majority
  PRODUCTS_DB_URL: mongodb+srv://Simha:Simha@cluster0.w56omxb.mongodb.net/Products?retryWrites=true&w=majority
  ORDERS_DB_URL: mongodb+srv://Simha:Simha@cluster0.w56omxb.mongodb.net/Orders?retryWrites=true&w=majority
  QUERY_DB_URL: mongodb+srv://Simha:Simha@cluster0.w56omxb.mongodb.net/QueryProducts?retryWrites=true&w=majority
  REVIEWS_DB_URL: mongodb+srv://Simha:Simha@cluster0.w56omxb.mongodb.net/Reviews?retryWrites=true&w=majority
