apiVersion: v1
kind: Service
metadata:
  name: orders-nodeport-srv
spec:
  selector:
    app: orders
  type: NodePort
  ports:
    - name: orders-nodeport-srv
      protocol: TCP
      port: 4004
      targetPort: 4004
      nodePort: 32323
