# @format

apiVersion: v1
kind: Service
metadata:
  name: products-nodeport-srv
spec:
  selector:
    app: products
  type: NodePort
  ports:
    - name: products-nodeport-srv
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 33334
